In [1]:
from Utilities.Confs.Configs import Configs
from Datasets.DSO.DsoDataset import DsoDatasetDataset
from Utilities.Visualizers.NoiseprintVisualizer import NoiseprintVisualizer

In [2]:
configs = Configs("config.yaml", "Fixing Exif")

In [3]:
dataset = DsoDatasetDataset(configs["global"]["datasets"]["root"])

DSO dataset


In [4]:
from Utilities.Visualizers.ExifVisualizer import ExifVisualizer

detector = ExifVisualizer()

WARNING  - From /home/gianlucadestefano/Deep-detectors-attacks/Utilities/Visualizers/ExifVisualizer.py:15: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.



Instructions for updating:
Use fn_output_signature instead


WARNING  - From /home/gianlucadestefano/Deep-detectors-attacks/venv/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:574: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead


Initializing graph on gpu 0
Instructions for updating:
Please use `layer.__call__` method instead.


WARNING  - From /home/gianlucadestefano/Deep-detectors-attacks/venv/lib/python3.8/site-packages/tf_slim/layers/layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer_v1) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.


affinity pred: (None, 83)
affinity pred: (None, 83)
/home/gianlucadestefano/Deep-detectors-attacks/Detectors/Exif/./ckpt/exif_final/exif_final.ckpt
INFO:tensorflow:Restoring parameters from /home/gianlucadestefano/Deep-detectors-attacks/Detectors/Exif/./ckpt/exif_final/exif_final.ckpt
unknown checkpoint string format /home/gianlucadestefano/Deep-detectors-attacks/Detectors/Exif/./ckpt/exif_final/exif_final.ckpt setting iteration to 0
Succesfully resuming from /home/gianlucadestefano/Deep-detectors-attacks/Detectors/Exif/./ckpt/exif_final/exif_final.ckpt
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


WARNING  - From /home/gianlucadestefano/Deep-detectors-attacks/Detectors/Exif/models/exif/exif_solver.py:91: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


WARNING  - `tf.train.start_queue_runners()` was called when no queue runners were defined. You can safely remove the call to this deprecated function.


In [5]:
sample_path = dataset.get_image('splicing-70.png')
detector.process_sample(sample_path)

Extracting features..
Completed in 1227.0750985145569s
Clustering...
Completed in 222.09455108642578s


In [6]:
detector.save_prediction_pipeline("exif-test.png")

done


In [7]:
print(detector.metadata["heatmap"])

[[0.10250826 0.10250826 0.10250826 ... 0.07397932 0.07397932 0.07397932]
 [0.10250826 0.10250826 0.10250826 ... 0.07397932 0.07397932 0.07397932]
 [0.10250826 0.10250826 0.10250826 ... 0.07397932 0.07397932 0.07397932]
 ...
 [0.40529048 0.40529048 0.40529048 ... 0.1563501  0.1563501  0.1563501 ]
 [0.40529048 0.40529048 0.40529048 ... 0.1563501  0.1563501  0.1563501 ]
 [0.40529048 0.40529048 0.40529048 ... 0.1563501  0.1563501  0.1563501 ]]
